DATASET_INPUT_FOLDER: "parse2022"
DATASET_OUTPUT_FOLDER: "parse2022_LC_48"
DATA_CROP_STRIDE: 24
DATA_CROP_SIZE: 48
LOWER_THRESHOLD_2D: 0.1
UPPER_THRESHOLD_2D: 0.9
TASK_TYPE: "LOCAL_CONNECTIVITY"
START_INDEX: 1
STOP_INDEX: 20


# Predict Pipeline:
APPLY_FUSION: True

APPLY_INPUT_MERGE_2D: False
APPLY_THRESHOLD_2D: True
THRESHOLD_2D: 0.2
APPLY_NOISE_FILTER_2D: False
HARD_NOISE_FILTER_2D: True
PREDICT_CONNECTIVITY_TYPE_2D: 4

APPLY_INPUT_MERGE_3D: True
APPLY_THRESHOLD_3D: True
THRESHOLD_3D: 0.5
APPLY_NOISE_FILTER_3D: True
HARD_NOISE_FILTER_3D: True
PREDICT_CONNECTIVITY_TYPE_3D: 6