DATASET_INPUT_FOLDER: "PipeForge3DPCD_Best"
DATASET_OUTPUT_FOLDER: "PipeForge3DPCD_Best_LC_48"
DATA_CROP_STRIDE: 24
DATA_CROP_SIZE: 48
LOWER_THRESHOLD_2D: 0.1
UPPER_THRESHOLD_2D: 0.9
TASK_TYPE: "LOCAL_CONNECTIVITY"  # "PATCH_HOLES"
START_INDEX: -1
STOP_INDEX: -1

# PCDs from PipeForge3D to Predict on Hospital CUP
# voxel size 1.0
# voxel scale 0.25


# Predict Pipeline:
# connectivity_type_3d = 26