DATASET_INPUT_FOLDER: "PipeForge3DPCD_Best"
DATASET_OUTPUT_FOLDER: "PipeForge3DPCD_Best_LC_32"
DATA_CROP_STRIDE: 16
DATA_CROP_SIZE: 32
LOWER_THRESHOLD_2D: 0.1
UPPER_THRESHOLD_2D: 0.9
TASK_TYPE: "LOCAL_CONNECTIVITY"
START_INDEX: -1
STOP_INDEX: -1

# PCDs from PipeForge3D
# voxel size 1.0
# voxel scale 0.25


# Predict Pipeline:
# apply_noise_filter_3d = True
# hard_noise_filter_3d = False
# connectivity_type_3d = 6