DATASET_INPUT_FOLDER: "parse2022"
DATASET_OUTPUT_FOLDER: "parse2022_SC_96"
DATA_CROP_STRIDE: 48
DATA_CROP_SIZE: 96
LOWER_THRESHOLD: 0.1
UPPER_THRESHOLD: 0.9
TASK_TYPE: "SINGLE_COMPONENT"
START_INDEX: 1
STOP_INDEX: 20