DATASET_INPUT_FOLDER: "parse2022"
DATASET_OUTPUT_FOLDER: "parse2022_SC_32"
DATA_CROP_STRIDE: 16
DATA_CROP_SIZE: 32
LOWER_THRESHOLD: 0.1
UPPER_THRESHOLD: 0.9
TASK_TYPE: "SINGLE_COMPONENT"
STOP_INDEX: 20