# Basic configuration for the parse2022 dataset with single component task type
DATASET_INPUT_FOLDER: "parse2022"
DATASET_OUTPUT_FOLDER: "parse2022_SC_32"
DATA_CROP_STRIDE: 32
DATA_CROP_SIZE: 32
LOWER_THRESHOLD: 0.1
UPPER_THRESHOLD: 0.9
TASK_TYPE: "SINGLE_COMPONENT"
START_INDEX: 1
STOP_INDEX: 50


# Predict Pipeline:
APPLY_FUSION: True

APPLY_INPUT_MERGE_2D: False
APPLY_THRESHOLD_2D: True
THRESHOLD_2D: 0.2
APPLY_NOISE_FILTER_2D: False
HARD_NOISE_FILTER_2D: True
PREDICT_CONNECTIVITY_TYPE_2D: 4

APPLY_INPUT_MERGE_3D: True
APPLY_THRESHOLD_3D: True
THRESHOLD_3D: 0.5
APPLY_NOISE_FILTER_3D: True
HARD_NOISE_FILTER_3D: True
PREDICT_CONNECTIVITY_TYPE_3D: 6