DATASET_INPUT_FOLDER: "parse2022"
DATASET_OUTPUT_FOLDER: "parse2022_LC_64"
DATA_CROP_STRIDE: 32
DATA_CROP_SIZE: 64
LOWER_THRESHOLD_2D: 0.1
UPPER_THRESHOLD_2D: 0.9
TASK_TYPE: "LOCAL_CONNECTIVITY"
STOP_INDEX: 20