DATASET_INPUT_FOLDER: "PipeForge3DPCD_V2"
DATASET_OUTPUT_FOLDER: "PipeForge3DPCD_LC_32_V2"
DATA_CROP_STRIDE: 16  # 48
DATA_CROP_SIZE: 32  # 96
LOWER_THRESHOLD_2D: 0.1
UPPER_THRESHOLD_2D: 0.9
TASK_TYPE: "LOCAL_CONNECTIVITY"  # "PATCH_HOLES"
STOP_INDEX: -1

# PCDs from PipeForge3D
# voxel size 1.0
# voxel scale 0.25