DATASET_FOLDER: "PipeForge3DMesh_32"
DATA_CROP_STRIDE: 16
DATA_CROP_SIZE: 32
LOWER_THRESHOLD_2D: 0.1
UPPER_THRESHOLD_2D: 0.9
TASK_TYPE: "PATCH_HOLES"

# Meshes from PipeForge3D with:
# voxel size 2.0
# voxel scale 0.5