DATASET_INPUT_FOLDER: "PipeForge3DPCD"
DATASET_OUTPUT_FOLDER: "PipeForge3DPCD_LC_32"
DATA_CROP_STRIDE: 16  # 48
DATA_CROP_SIZE: 32  # 96
LOWER_THRESHOLD_2D: 0.1
UPPER_THRESHOLD_2D: 0.9
TASK_TYPE: "LOCAL_CONNECTIVITY"  # "PATCH_HOLES"
START_INDEX: -1
STOP_INDEX: -1

# PCDs from PipeForge3D
