DATASET_INPUT_FOLDER: "PipeForge3DPCD"
DATASET_OUTPUT_FOLDER: "PipeForge3DPCD_SC_32"
DATA_CROP_STRIDE: 16  # 48
DATA_CROP_SIZE: 32  # 96
LOWER_THRESHOLD_2D: 0.1
UPPER_THRESHOLD_2D: 0.9
TASK_TYPE: "SINGLE_COMPONENT"
STOP_INDEX: -1

# PCDs from PipeForge3D (in Tree Mode)
