DATASET_INPUT_FOLDER: "parse2022"
DATASET_OUTPUT_FOLDER: "parse2022_LC_96_50"
DATA_CROP_STRIDE: 96
DATA_CROP_SIZE: 96
LOWER_THRESHOLD_2D: 0.1
UPPER_THRESHOLD_2D: 0.9
TASK_TYPE: "LOCAL_CONNECTIVITY"
START_INDEX: 1
STOP_INDEX: 50


# Predict Pipeline:
# connectivity_type_3d = 6